version: '3.9'

services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: careeruser
      MONGO_INITDB_ROOT_PASSWORD: careerpass
      MONGO_INITDB_DATABASE: careerdb
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass careerpass

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"   # management UI at http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: careeruser
      RABBITMQ_DEFAULT_PASS: careerpass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongo_data:
  rabbitmq_data:
