server:
  port: 8082

spring:
  application:
    name: search-service

  data:
    mongodb:
      uri: ${MONGO_URI:}
      database: ${MONGO_DATABASE:careerdb}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://cognito-idp.${AWS_REGION:us-east-1}.amazonaws.com/${COGNITO_USER_POOL_ID:local}/.well-known/jwks.json

services:
  job-service-url: ${JOB_SERVICE_URL:http://localhost:8081}
