server:
  port: 8085

spring:
  application:
    name: ai-agent-service

  jackson:
    serialization:
      write-dates-as-timestamps: false

  data:
    mongodb:
      uri: ${MONGO_URI:}
      database: ${MONGO_DATABASE:careerdb}

gemini:
  api-key: ${GEMINI_API_KEY}
  base-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
  model: gemini-2.5-flash

services:
  search-service-url: ${SEARCH_SERVICE_URL:http://localhost:8082}
  job-service-url: ${JOB_SERVICE_URL:http://localhost:8081}
